include $(THEOS)/makefiles/common.mk
BUNDLE_NAME = ColdWhitePrefs
ColdWhitePrefs_FILES = CWRootListController.m
ColdWhitePrefs_RESOURCE_FILES = Info.plist
ColdWhitePrefs_INSTALL_PATH = /Library/PreferenceBundles
ColdWhitePrefs_CFLAGS = -fobjc-arc -I.
ColdWhitePrefs_LDFLAGS = -undefined dynamic_lookup
include $(THEOS_MAKE_PATH)/bundle.mk
